In [1]:
import torch

In [2]:
# 创建固定种子的生成器
generator = torch.Generator()
generator.manual_seed(42)  # 设置种子为 42

# 使用这个生成器
w = torch.empty(3, 5)
print(torch.nn.init.normal_(w, generator=generator))

# 直接再次使用相同的生成器不会产生相同的随机数
w2 = torch.empty(3, 5)
print(torch.nn.init.normal_(w2, generator=generator))

print(torch.allclose(w, w2))  # 输出：False（生成器状态已改变）

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898, -0.9890]])
tensor([[ 0.9580,  1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950,  0.2815],
        [ 0.0562,  0.5227, -0.2384, -0.0499,  0.5263]])
False


In [3]:
#-----------#
# 创建固定种子的生成器
generator = torch.Generator()
generator.manual_seed(42)  # 设置种子为 42
# 使用这个生成器
w = torch.empty(3, 5)
print(torch.nn.init.normal_(w, generator=generator))

# 再次设置相同的生成器
generator = torch.Generator()
generator.manual_seed(42)  # 设置种子为 42
#再次使用,产生相同的随机数
w2 = torch.empty(3, 5)
print(torch.nn.init.normal_(w2, generator=generator))

print(torch.allclose(w, w2))  # 输出：True（生成器状态未改变）

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898, -0.9890]])
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898, -0.9890]])
True
